apiVersion: v1
data:
  PROXMOX_PASSWORD: D0m0Arigato!
  PROXMOX_SECRET: ""
  PROXMOX_TOKENID: ""
  PROXMOX_USER: root
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cappx-test
  name: cappx-test
  namespace: default
type: Opaque
