apiVersion: v1
kind: Pod
metadata:
  name: resources-example
spec:
  initContainers:
  - name: setup
    image: registry.k8s.io/busybox:1.27.2
    command: ["sh", "-c", "echo setting up"]
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        memory: 64Mi
  - name: log-shipper
    image: registry.k8s.io/busybox:1.27.2
    restartPolicy: Always
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi
  containers:
  - name: app
    image: nginx:1.29
    resources:
      requests:
        cpu: 300m
        memory: 128Mi
      limits:
        memory: 128Mi
