/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Checks that the KYAML rendering of each example manifest, generated by
// scripts/kyaml.sh, describes the same objects as the conventional YAML it was
// rendered from. Pages carry both dialects, so a reader who copies either one
// has to end up with the same cluster state.
//
// Which manifests have a counterpart at all is scripts/kyaml.sh's business:
// `scripts/kyaml.sh verify` renders the tree afresh and diffs it, which catches
// a counterpart that is missing, left behind, or edited by hand. This walks what
// is there and asks only whether it still says the same thing.
//
// That diff cannot answer this question in its place. It compares a freshly
// rendered tree against the committed one, so both sides come from the same
// formatter, and a formatter that changed a manifest's meaning would agree with
// itself. Only comparing a manifest against its counterpart catches that.
//
// This lives outside content/<lang>/examples on purpose: the tests there import
// k8s.io/kubernetes for schema validation, which needs a Kubernetes source tree
// beside this one, whereas this test needs only a YAML parser and so runs
// wherever scripts/kyaml.sh does. `scripts/kyaml.sh verify` runs it.
package kyaml_test

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"gopkg.in/yaml.v3"
)

// Relative to this file, since `go test` runs in the package directory.
const contentDir = "../../content"

// Decodes every document in a KYAML or YAML file into plain Go values. KYAML is
// a subset of YAML, so one decoder reads both, and two files describing the
// same objects decode to equal values whatever their dialect, quoting or
// comments.
func decodeDocs(path string) ([]interface{}, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var docs []interface{}
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	for {
		var doc interface{}
		err := decoder.Decode(&doc)
		if err == io.EOF {
			return docs, nil
		}
		if err != nil {
			return nil, fmt.Errorf("document %d: %w", len(docs), err)
		}
		// A file may end with a bare separator, or hold a wholly commented-out
		// document; neither carries anything to compare.
		if doc == nil {
			continue
		}
		docs = append(docs, doc)
	}
}

// Echoes the languages with a generated KYAML tree.
func languages(t *testing.T) []string {
	entries, _ := filepath.Glob(filepath.Join(contentDir, "*", "examples-kyaml"))
	if len(entries) == 0 {
		t.Fatal("no content/*/examples-yaml directory; run: scripts/kyaml.sh generate")
	}
	var langs []string
	for _, entry := range entries {
		langs = append(langs, filepath.Base(filepath.Dir(entry)))
	}
	return langs
}

func TestKYAMLMatchesYAML(t *testing.T) {
	for _, lang := range languages(t) {
		t.Run(lang, func(t *testing.T) {
			sourceDir := filepath.Join(contentDir, lang, "examples")
			generatedDir := filepath.Join(contentDir, lang, "examples-kyaml")
			compared := 0

			err := filepath.WalkDir(generatedDir, func(path string, entry fs.DirEntry, err error) error {
				if err != nil || entry.IsDir() {
					return err
				}
				rel, err := filepath.Rel(generatedDir, path)
				if err != nil {
					return err
				}
				source := filepath.Join(sourceDir, rel)

				want, err := decodeDocs(source)
				if err != nil {
					t.Errorf("%s did not decode correctly: %v", source, err)
					return nil
				}
				got, err := decodeDocs(path)
				if err != nil {
					t.Errorf("%s did not decode correctly: %v", path, err)
					return nil
				}
				compared++

				if len(want) != len(got) {
					t.Errorf("%s holds %d document(s), its KYAML rendering holds %d", rel, len(want), len(got))
					return nil
				}
				for i := range want {
					if !reflect.DeepEqual(want[i], got[i]) {
						t.Errorf("%s and its KYAML rendering describe different objects, in document %d", rel, i)
					}
				}
				return nil
			})
			if err != nil {
				t.Fatalf("could not walk %s: %v", generatedDir, err)
			}
			if compared == 0 {
				t.Errorf("compared no manifests under %s", generatedDir)
			}
			t.Logf("compared %d manifests", compared)
		})
	}
}
