apiVersion: v1
kind: Pod
metadata:
  name: expandable-pvc-pod
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: expandable-pvc
