---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "example-redis-config",
  },
  data: {
    redis-config: "\
       maxmemory 2mb\n\
       maxmemory-policy allkeys-lru\n\
      ",
  },
}
