#!/usr/bin/env bash
set -euo pipefail

REPO="${REPO:-YOUR_USERNAME/website}"          # override via env
BASE_REF="${BASE_REF:-main}"
WIKI_REPO="https://github.com/${REPO}.wiki.git"
WIKI_DIR="$(mktemp -d)/wiki"
WIKI_PAGE="Draft-Blogs.md"

echo "Scanning ${REPO} for blog posts with draft:true on ${BASE_REF}..."
echo

# Step 1: Find all draft blogs from main file tree
gh api "repos/${REPO}/git/trees/${BASE_REF}?recursive=1" \
  --jq '.tree[].path' \
| grep -E '^content/en/blog/_posts/.+/index\.md$' \
| while read -r path; do

  content="$(gh api \
    -H "Accept: application/vnd.github.raw" \
    "repos/${REPO}/contents/${path}?ref=${BASE_REF}" 2>/dev/null || true)"

  [ -z "$content" ] && continue
  echo "$content" | grep -q '"status":"404"' && continue

  DRAFT_LINE=$(echo "$content" | grep -iE '^draft:[[:space:]]*true[[:space:]]*$' || true)
  [ -z "$DRAFT_LINE" ] && continue

  TITLE=$(echo "$content" | grep -m1 -E '^title:' \
    | sed 's/^title:[[:space:]]*//' | tr -d '"'"'" || echo "(no title)")
  GH_URL="https://github.com/${REPO}/blob/${BASE_REF}/${path}"

  echo "| ${TITLE} | \`${path}\` | [View](${GH_URL}) |"

done > /tmp/draft_rows.txt

ROW_COUNT=$(wc -l < /tmp/draft_rows.txt | tr -d ' ')

if [ "$ROW_COUNT" -eq 0 ]; then
  echo "No draft blogs found."
  exit 0
fi

echo "Found ${ROW_COUNT} draft blog(s). Updating wiki..."

# Step 2: Clone wiki
git clone "$WIKI_REPO" "$WIKI_DIR"

# Step 3: Generate wiki page
cat > "${WIKI_DIR}/${WIKI_PAGE}" <<EOF
# Draft Blog Posts (Merged but Unpublished)

> Auto-generated by \`find-draft-blogs.sh\` · Last updated: $(date -u '+%Y-%m-%d %H:%M UTC')

These blog posts have been **merged into main** but still have \`draft: true\` in their front matter — not yet live on the site.

## Pending Publication

| Title | Path | Link |
|-------|------|------|
$(cat /tmp/draft_rows.txt)

## How to publish

1. Open a PR removing \`draft: true\` from the file's front matter
2. Get it reviewed and merged
3. Blog goes live on next site build
EOF

# Step 4: Commit and push
cd "$WIKI_DIR"
git config user.email "you@example.com"
git config user.name "Draft Blog Bot"
git add "$WIKI_PAGE"
git diff --cached --quiet && echo "No changes to wiki." && exit 0
git commit -m "chore: update draft blog list [$(date -u '+%Y-%m-%d')]"
git push

echo ""
echo "✓ Wiki updated: https://github.com/${REPO}/wiki/$(basename $WIKI_PAGE .md)"

# Cleanup
rm -rf "$WIKI_DIR" /tmp/draft_rows.txt


# Just scan and print — no wiki push yet
