apiVersion: v1
kind: Pod
metadata:
  name: grpc-tls-app
spec:
  containers:
  - name: app
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    command: ["/agnhost", "grpc-health-checking", "--port=8443"]
    ports:
    - containerPort: 8443
    livenessProbe:
      grpc:
        port: 8443
        mode: TLS
      initialDelaySeconds: 5
      periodSeconds: 10
