---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "fluentd-config",
  },
  data: {
    fluentd.conf: "\
       <source>\n\
      \  type tail\n\
      \  format none\n\
      \  path /var/log/1.log\n\
      \  pos_file /var/log/1.log.pos\n\
      \  tag count.format1\n\
       </source>\n\
       \n\
       <source>\n\
      \  type tail\n\
      \  format none\n\
      \  path /var/log/2.log\n\
      \  pos_file /var/log/2.log.pos\n\
      \  tag count.format2\n\
       </source>\n\
       \n\
       <match **>\n\
      \  type google_cloud\n\
       </match>\n\
      ",
  },
}
