flowchart TD
    A(Create Policy\ninstance) -->|annotate namespace\nto validate signatures| B(Create Pod)
    B --> C[policy evaluation]
    C --> D[fa:fa-check Admitted]
    C --> E[fa:fa-xmark Not admitted]
    D --> |if necessary| F[Image Pull]
