# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Azure App Service deployments: https://aka.ms/webapps-deploy

name: Build and deploy site to Azure Web App - lesslikely

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive --depth 1

      - name: Install Node dependencies
        run: npm ci

      - name: Build site
        run: make production-build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: site
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B9B6019BE084427AC79CEB2E35FD1C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5EC8A33405A54A59A4186867C134CDC0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46CFDB50AE514A41B0F8923080201CAA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lesslikely'
          slot-name: 'Production'
          package: public
