---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "mysql",
    labels: {
      app: "mysql",
      app.kubernetes.io/name: "mysql",
    },
  },
  data: {
    primary.cnf: "\
       # Apply this config only on the primary.\n\
       [mysqld]\n\
       log-bin\n\
      ",
    replica.cnf: "\
       # Apply this config only on replicas.\n\
       [mysqld]\n\
       super-read-only\n\
      ",
  },
}
